# Generated by Django 5.1 on 2024-08-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_study_numberofwords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='study',
            name='date',
            field=models.DateField(verbose_name='Study Date'),
        ),
    ]
