# Generated by Django 5.1 on 2024-08-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='name',
            new_name='word',
        ),
        migrations.AddField(
            model_name='word',
            name='color',
            field=models.CharField(default='green', max_length=20),
        ),
        migrations.AlterField(
            model_name='word',
            name='grade',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=1),
        ),
    ]
