# Generated by Django 5.1 on 2024-08-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_speller_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='adulthelp',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
        ),
    ]
