# Generated by Django 5.1 on 2024-08-26 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spellers',
            new_name='Speller',
        ),
    ]
