# Generated by Django 5.1 on 2024-08-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_study_adulthelp'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='speller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.speller'),
            preserve_default=False,
        ),
    ]
